pipeline {
  agent any 
  stages {
    satge("build") {
      steps {
        echo "This is build stage"
      }
      
  }
  stages {
    stage("Test") {
      steps {
        echo "This is test stage"
      }
    }
  }
}
}
